"""
PDF export service — generates a full consultation PDF report.
Uses fpdf2 for clean, structured output.

Each session in `sessions` may carry pre-processed enrichments:
  - session['ai_summary']                   : dict | None   (pre-generated AI summary)
  - session['session_documents'][*]['image_pages'] : list[bytes]  (pre-rendered PNG pages)

When these are absent the function gracefully degrades:
  - Images are fetched on-the-fly from public_url (jpg/png only)
  - PDFs without pre-rendered pages fall back to a link row
  - Missing ai_summary section is simply omitted
"""
import io
import os
import logging
from fpdf import FPDF
from datetime import datetime
from typing import Any

from app.database import get_supabase

logger = logging.getLogger(__name__)

# Core fonts (Helvetica etc.) only support latin-1.
# Replace common Unicode punctuation with safe ASCII equivalents.
_UNICODE_MAP = str.maketrans({
    "\u2014": "-",   # em dash
    "\u2013": "-",   # en dash
    "\u2018": "'",   # left single quotation mark
    "\u2019": "'",   # right single quotation mark
    "\u201c": '"',   # left double quotation mark
    "\u201d": '"',   # right double quotation mark
    "\u2022": "*",   # bullet
    "\u2026": "...", # ellipsis
})


def _s(text: str) -> str:
    """Sanitize text for latin-1 fpdf core fonts."""
    if not isinstance(text, str):
        text = str(text) if text is not None else ""
    return text.translate(_UNICODE_MAP).encode("latin-1", errors="replace").decode("latin-1")


class AarogyanPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(26, 107, 90)
        self.cell(0, 12, _s("Aarogyan - Consultation Report"), align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(26, 107, 90)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(107, 114, 128)
        self.cell(
            0, 10,
            _s(f"Page {self.page_no()} | Generated by Aarogyan | {datetime.now().strftime('%d %b %Y')}"),
            align="C",
        )

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(232, 245, 240)
        self.set_text_color(26, 107, 90)
        self.cell(0, 10, _s(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def sub_section_title(self, title: str):
        self.set_font("Helvetica", "B", 10)
        self.set_fill_color(244, 250, 248)
        self.set_text_color(26, 107, 90)
        self.cell(0, 8, _s(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def field_row(self, label: str, value: str):
        label_w = 45
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(26, 26, 46)
        self.set_x(self.l_margin)
        self.cell(label_w, 7, _s(label + ":"), new_x="RIGHT", new_y="LAST")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(self.epw - label_w, 7, _s(str(value) if value is not None else "-"))

    def ai_summary_block(self, summary: dict):
        """Render a highlighted AI summary section for a session."""
        self.set_fill_color(248, 253, 250)
        self.set_draw_color(26, 107, 90)

        # Header bar
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(26, 107, 90)
        self.set_fill_color(220, 242, 235)
        self.cell(0, 8, _s("  AI Session Summary"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

        progression = summary.get("progression", "")
        if progression:
            prog_labels = {
                "improving": "Improving",
                "worsening": "Worsening",
                "unchanged": "Unchanged",
                "first_visit": "First Visit",
            }
            prog_text = prog_labels.get(progression, progression.title())
            prog_colors = {
                "improving": (34, 139, 34),
                "worsening": (180, 50, 50),
                "unchanged": (107, 114, 128),
                "first_visit": (26, 107, 90),
            }
            r, g, b = prog_colors.get(progression, (107, 114, 128))
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(r, g, b)
            self.set_x(self.l_margin + 4)
            self.cell(0, 6, _s(f"Progression: {prog_text}"), new_x="LMARGIN", new_y="NEXT")

        summary_text = summary.get("summary", "")
        if summary_text:
            self.set_font("Helvetica", "I", 10)
            self.set_text_color(40, 40, 40)
            self.set_x(self.l_margin + 4)
            self.multi_cell(self.epw - 8, 6, _s(summary_text))
            self.ln(1)

        key_symptoms = summary.get("key_symptoms") or []
        if key_symptoms:
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(26, 26, 46)
            self.set_x(self.l_margin + 4)
            self.cell(0, 5, _s("Key Symptoms:"), new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 9)
            for sym in key_symptoms:
                self.set_x(self.l_margin + 8)
                self.cell(0, 5, _s(f"* {sym}"), new_x="LMARGIN", new_y="NEXT")
            self.ln(1)

        treatment = summary.get("treatment_given", "")
        if treatment:
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(26, 26, 46)
            self.set_x(self.l_margin + 4)
            self.cell(0, 5, _s("Treatment Given:"), new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 9)
            self.set_x(self.l_margin + 8)
            self.multi_cell(self.epw - 12, 5, _s(treatment))
            self.ln(1)

        findings = summary.get("important_findings") or []
        if findings:
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(26, 26, 46)
            self.set_x(self.l_margin + 4)
            self.cell(0, 5, _s("Important Findings:"), new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 9)
            for finding in findings:
                self.set_x(self.l_margin + 8)
                self.cell(0, 5, _s(f"* {finding}"), new_x="LMARGIN", new_y="NEXT")
            self.ln(1)

        # Disclaimer note
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.set_x(self.l_margin + 4)
        self.cell(
            0, 4,
            _s("AI-generated summary — does not replace clinical judgment."),
            new_x="LMARGIN", new_y="NEXT",
        )
        self.ln(3)
        self.set_text_color(26, 26, 46)

    def embed_image_pages(self, pages: list[bytes], doc_name: str):
        """Embed one or more pre-rendered PNG pages for a document."""
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(80, 80, 80)
        self.set_x(self.l_margin + 4)
        label = _s(f"* {doc_name}")
        self.cell(0, 6, label, new_x="LMARGIN", new_y="NEXT")
        for idx, page_bytes in enumerate(pages):
            try:
                img_io = io.BytesIO(page_bytes)
                if len(pages) > 1:
                    self.set_font("Helvetica", "I", 7)
                    self.set_text_color(120, 120, 120)
                    self.set_x(self.l_margin + 8)
                    self.cell(0, 4, _s(f"Page {idx + 1}"), new_x="LMARGIN", new_y="NEXT")
                self.image(img_io, x=self.l_margin + 8, w=min(160, self.epw - 8))
                self.ln(3)
            except Exception as e:
                logger.warning("Could not embed image page %d for %s: %s", idx + 1, doc_name, e)
        self.set_text_color(26, 26, 46)

    def doc_link_row(self, name: str, url: str):
        """Fallback: render a document row with a clickable URL (no image available)."""
        self.set_font("Helvetica", "", 9)
        self.set_text_color(80, 80, 80)
        self.set_x(self.l_margin + 4)
        self.cell(0, 6, _s(f"* {name}"), new_x="LMARGIN", new_y="NEXT")
        if url:
            self.set_x(self.l_margin + 8)
            self.set_font("Helvetica", "U", 8)
            self.set_text_color(26, 107, 90)
            safe_url = url if url.startswith("http") else ""
            self.cell(0, 5, _s("View Document"), link=safe_url, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(26, 26, 46)

    def divider(self):
        self.set_draw_color(200, 220, 215)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)


def _download_from_storage(storage_path: str) -> bytes | None:
    """Download a file from Supabase 'documents' bucket using service-role key."""
    try:
        return get_supabase().storage.from_("documents").download(storage_path)
    except Exception as e:
        logger.warning("Could not download from storage path %s: %s", storage_path, e)
        return None


async def generate_consultation_pdf(
    consultation: dict[str, Any],
    sessions: list[dict[str, Any]],
) -> bytes:
    """Build the full consultation PDF.

    When sessions are enriched by consultation_pdf_service (background rebuild):
      - session['ai_summary']                           : pre-generated dict
      - session['session_documents'][*]['image_pages']  : pre-rendered list[bytes]

    When called on-demand (export fallback), enrichments may be absent:
      - AI summary section is skipped
      - jpg/png images are fetched live from public_url; PDFs fall back to link
    """
    pdf = AarogyanPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Consultation header ─────────────────────────────────────────────────
    pdf.section_title("Consultation Overview")
    pdf.field_row("Name", consultation.get("name", ""))
    pdf.field_row("Start Date", consultation.get("start_date", "") or "-")
    if consultation.get("notes"):
        pdf.field_row("Notes", consultation["notes"])
    pdf.ln(4)

    if not sessions:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, _s("No sessions recorded."), new_x="LMARGIN", new_y="NEXT")
    else:
        for i, session in enumerate(sessions, start=1):
            pdf.section_title(f"Session {i}  -  {session.get('visit_date', 'Unknown Date')}")

            # ── Session fields ──────────────────────────────────────────────
            if session.get("symptoms"):
                pdf.field_row("Symptoms", session["symptoms"])
            if session.get("diagnosis"):
                pdf.field_row("Diagnosis", session["diagnosis"])
            if session.get("medications"):
                pdf.field_row("Medications", session["medications"])
            if session.get("doctor_notes"):
                pdf.field_row("Doctor Notes", session["doctor_notes"])

            # ── AI Summary ──────────────────────────────────────────────────
            ai_summary = session.get("ai_summary")
            if ai_summary and isinstance(ai_summary, dict):
                pdf.ln(2)
                pdf.ai_summary_block(ai_summary)

            # ── Documents ───────────────────────────────────────────────────
            docs = session.get("session_documents") or []
            if docs:
                pdf.sub_section_title("Attached Documents")
                for doc in docs:
                    name = doc.get("file_name", "Unknown file")
                    url = doc.get("public_url", "") or ""
                    ext = os.path.splitext(name)[1].lower()

                    # Pre-rendered image pages (from background enrichment)
                    image_pages: list[bytes] = doc.get("image_pages") or []
                    storage_path = doc.get("storage_path") or ""

                    if image_pages:
                        pdf.embed_image_pages(image_pages, name)
                    elif ext in (".jpg", ".jpeg", ".png") and storage_path:
                        # On-demand fallback: download directly from storage
                        img_bytes = _download_from_storage(storage_path)
                        if img_bytes:
                            pdf.embed_image_pages([img_bytes], name)
                        else:
                            pdf.doc_link_row(name, url)
                    elif ext == ".pdf" and storage_path:
                        # On-demand PDF: render pages via PyMuPDF
                        try:
                            import fitz
                            pdf_bytes_doc = _download_from_storage(storage_path)
                            if pdf_bytes_doc:
                                fitz_doc = fitz.open(stream=pdf_bytes_doc, filetype="pdf")
                                pages = []
                                for pg in fitz_doc:
                                    pix = pg.get_pixmap(matrix=fitz.Matrix(1.5, 1.5), alpha=False)
                                    pages.append(pix.tobytes("png"))
                                fitz_doc.close()
                                pdf.embed_image_pages(pages, name)
                            else:
                                pdf.doc_link_row(name, url)
                        except Exception as e:
                            logger.warning("On-demand PDF render failed for %s: %s", name, e)
                            pdf.doc_link_row(name, url)
                    else:
                        pdf.doc_link_row(name, url)

                pdf.set_text_color(26, 26, 46)

            if i < len(sessions):
                pdf.divider()

        pdf.ln(4)

    # ── Disclaimer ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.multi_cell(
        0, 6,
        _s(
            "This document is a personal health record exported from Aarogyan and is not a medical "
            "certificate. AI-generated summaries are for informational purposes only and do not "
            "replace professional medical advice. Always consult a qualified healthcare provider."
        ),
    )

    return bytes(pdf.output())

